language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t belmont120/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true belmont120/docker-react npm run test -- --coverage
